version: "3.3"

services:
  api:
    container_name: api
    ports:
      - 3001:3000
    build:
      context: ./
      dockerfile: Dockerfile
    command: npm run start:api
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
