version: "3.3"

services:
  api:
    container_name: api
    ports:
      - 3001:3000
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    command: npm run start:api
    volumes:
      - ./:/app
      - node_modules_api:/app/node_modules
  frontend:
    container_name: frontend
    ports:
      - 4200:4200
    build:
      context: ./
      dockerfile: ./apps/frontend/Dockerfile
    command: npm run start:frontend
    volumes:
      - ./:/app
      - node_modules_frontend:/app/node_modules


volumes:
  node_modules_api:
  node_modules_frontend:
