version: "3.3"

services:
  api:
    container_name: api
    ports:
      - 3001:3000
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    command: npm run start:api
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
  frontend:
    container_name: frontend
    ports:
      - 3002:3000
    build:
      context: ./
      dockerfile: ./apps/frontend/Dockerfile
    command: npm run start:frontend
    volumes:
      - ./:/app
      - node_modules:/app/node_modules


volumes:
  node_modules:
