version: "3.3"

services:
  api:
    container_name: ts_practice_api
    ports:
      - 3001:3000
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    command: npm run start:api
    volumes:
      - ./:/app
      - node_modules_api:/app/node_modules
    depends_on:
      - db
  frontend:
    container_name: ts_practice_frontend
    ports:
      - 4200:4200
    build:
      context: ./
      dockerfile: ./apps/frontend/Dockerfile
    command: npm run start:frontend
    volumes:
      - ./:/app
      - node_modules_frontend:/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:8.0.25
    platform: linux/x86_64
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ts_practice_db
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_USER: 'practice_user'
      MYSQL_DATABASE: 'practice'
      MYSQL_PASSWORD: 'password'
    volumes:
      - db_data:/var/lib/mysql
  mailer:
    image: tophfr/mailcatcher
    container_name: ts_practice_mailcatcher
    ports:
      - '1080:80'
      - '1025:25'

volumes:
  node_modules_api:
  node_modules_frontend:
  db_data:
